"""Remove cw string

Revision ID: 03ecc716a68a
Revises: e7323ee0414d
Create Date: 2022-04-13 00:39:18.341139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ecc716a68a'
down_revision = 'e7323ee0414d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('content_warning')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_warning', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
