"""User reports with reason

Revision ID: 0a1708abeb1a
Revises: bc1cc24d929e
Create Date: 2022-04-07 16:15:27.031153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1708abeb1a'
down_revision = 'bc1cc24d929e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('reason')

    # ### end Alembic commands ###
