"""Content tag stub

Revision ID: 0fa3a4450c6c
Revises: 8e36a759be69
Create Date: 2022-04-16 21:12:13.048098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
from app.dl.helpers import make_stub

revision = '0fa3a4450c6c'
down_revision = '8e36a759be69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from app.serve.db import ContentTag
    # with op.batch_alter_table('content_tags', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('stub', sa.String(), nullable=False, server_default="stub"))

    conn = op.get_bind()
    session = Session(bind=conn)

    op.add_column('content_tags', sa.Column('stub', sa.String(length=50), nullable=True))

    for item in session.query(ContentTag).filter_by(stub=None):
        item.stub = make_stub(item.name)
    session.commit()

    op.create_unique_constraint('unique_stub', 'content_tags', ['stub'])

    op.alter_column(
        table_name='content_tags',
        column_name='stub',
        nullable=False
    )

    # with op.batch_alter_table('content_tags', schema=None) as batch_op:
    #     batch_op.create_unique_constraint(None, ['stub'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stub')

    # ### end Alembic commands ###
