"""Categories on videos

Revision ID: 23bc3b669469
Revises: 47a3bcd7f9e3
Create Date: 2022-03-30 18:53:55.088361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23bc3b669469'
down_revision = '47a3bcd7f9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
