"""Processed fields

Revision ID: 285eb0410c70
Revises: 0a1708abeb1a
Create Date: 2022-04-08 09:01:44.820263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285eb0410c70'
down_revision = '0a1708abeb1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_video_format', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('processed_audio_format', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('processed_bit_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processed_frame_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('processed_file_size', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('processed_file_size')
        batch_op.drop_column('processed_frame_rate')
        batch_op.drop_column('processed_bit_rate')
        batch_op.drop_column('processed_audio_format')
        batch_op.drop_column('processed_video_format')

    # ### end Alembic commands ###
