"""New initial

Revision ID: 33a82e44aa64
Revises: 
Create Date: 2022-04-18 04:53:11.416348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33a82e44aa64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #with op.batch_alter_table('videos', schema=None) as batch_op:
        # batch_op.drop_constraint('videos_theatre_id_fkey', type_='foreignkey')
        #batch_op.drop_column('theatre_id')
    op.drop_table('theatres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theatres',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stub', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('from_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('to_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ongoing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('logo_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='theatres_pkey'),
    sa.UniqueConstraint('name', name='theatres_name_key'),
    sa.UniqueConstraint('stub', name='theatres_stub_key')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theatre_id', sa.INTEGER(), autoincrement=False, nullable=True))
        # batch_op.create_foreign_key('videos_theatre_id_fkey', 'theatres', ['theatre_id'], ['id'])

    # ### end Alembic commands ###
