"""Faile downloads, orig upload

Revision ID: 4236cf168e53
Revises: c24c1e1187c9
Create Date: 2022-04-15 16:10:50.687431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4236cf168e53'
down_revision = 'c24c1e1187c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failed')
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orig_upload_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('orig_upload_time')

    op.create_table('failed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_warning', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='failed_pkey')
    )
    # ### end Alembic commands ###
