"""Change duplicate relationship

Revision ID: 4523ba865102
Revises: 5d888708a62c
Create Date: 2022-04-07 00:24:33.254216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4523ba865102'
down_revision = '5d888708a62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_duplicates',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_id'], ['videos.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('video_id', 'duplicate_id')
    )
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint('videos_duplicate_of_id_fkey', type_='foreignkey')
        batch_op.drop_column('duplicate_of_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_of_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('videos_duplicate_of_id_fkey', 'videos', ['duplicate_of_id'], ['id'])

    op.drop_table('video_duplicates')
    # ### end Alembic commands ###
