"""Category on content tag

Revision ID: 47a3bcd7f9e3
Revises: 18f5c78c1cad
Create Date: 2022-03-30 17:18:18.008166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a3bcd7f9e3'
down_revision = '18f5c78c1cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_tags', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
