"""Failed downloads

Revision ID: 4a6e634d0566
Revises: 8f1c0c79f92b
Create Date: 2022-03-20 16:53:03.713722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6e634d0566'
down_revision = '8f1c0c79f92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
