"""New video fields

Revision ID: 5d888708a62c
Revises: ca27241da302
Create Date: 2022-04-02 17:43:46.149258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d888708a62c'
down_revision = 'ca27241da302'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
