"""Add token model

Revision ID: 6015af7140fc
Revises: ef5be7a7c9e3
Create Date: 2022-03-19 18:16:28.099881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6015af7140fc'
down_revision = 'ef5be7a7c9e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
