"""Theatres

Revision ID: 620005352f4a
Revises: ec2b4a3d8480
Create Date: 2022-04-18 04:30:07.530439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620005352f4a'
down_revision = 'ec2b4a3d8480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
