"""Hybrid methods

Revision ID: 634c07b6db66
Revises: 4640f991c547
Create Date: 2022-04-16 01:45:30.971827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634c07b6db66'
down_revision = '4640f991c547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
