"""False positives

Revision ID: 6a286dd49df1
Revises: cceec84d3340
Create Date: 2022-04-15 23:18:54.799910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a286dd49df1'
down_revision = 'cceec84d3340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('false_positive_association', schema=None) as batch_op:
        batch_op.alter_column('left_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('right_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('false_positive_association', schema=None) as batch_op:
        batch_op.alter_column('right_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('left_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
