"""Hybrid methods

Revision ID: 7e1c84c92e39
Revises: 871993feb6e1
Create Date: 2022-04-16 01:36:23.872620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1c84c92e39'
down_revision = '871993feb6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
