"""Hybrid methods

Revision ID: 7f9c62fbb343
Revises: e4fb334d0a61
Create Date: 2022-04-16 02:06:32.019046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9c62fbb343'
down_revision = 'e4fb334d0a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
