"""User report date

Revision ID: 83dea6fa9a86
Revises: 4236cf168e53
Create Date: 2022-04-15 16:12:55.917224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dea6fa9a86'
down_revision = '4236cf168e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from datetime import datetime
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(), nullable=False, server_default=""))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('report_time')

    # ### end Alembic commands ###
