"""Hybrid methods

Revision ID: 871993feb6e1
Revises: 6a286dd49df1
Create Date: 2022-04-16 01:15:17.120091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871993feb6e1'
down_revision = '6a286dd49df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
