"""Hybrid methods

Revision ID: 8e36a759be69
Revises: 7f9c62fbb343
Create Date: 2022-04-16 02:07:06.343330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e36a759be69'
down_revision = '7f9c62fbb343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
