"""Remove safe to store

Revision ID: 999adb8b9abe
Revises: 23bc3b669469
Create Date: 2022-04-02 15:54:16.024899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999adb8b9abe'
down_revision = '23bc3b669469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('safe_to_store')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safe_to_store', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
