"""Category stub

Revision ID: b2af0d206d30
Revises: 0fa3a4450c6c
Create Date: 2022-04-16 21:20:14.222839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
from app.dl.helpers import make_stub

# revision identifiers, used by Alembic.
revision = 'b2af0d206d30'
down_revision = '0fa3a4450c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from app.serve.db import Category
    conn = op.get_bind()
    session = Session(bind=conn)

    op.add_column('categories', sa.Column('stub', sa.String(length=50), nullable=True))

    for item in session.query(Category).filter_by(stub=None):
        item.stub = make_stub(item.name)
    session.commit()

    op.create_unique_constraint('unique_cat_stub', 'categories', ['stub'])

    op.alter_column(
        table_name='categories',
        column_name='stub',
        nullable=False
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_tags', schema=None) as batch_op:
        batch_op.alter_column('stub',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stub')

    # ### end Alembic commands ###
