"""Hybrid methods

Revision ID: b6c310055646
Revises: 7e1c84c92e39
Create Date: 2022-04-16 01:38:55.900906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c310055646'
down_revision = '7e1c84c92e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
