"""New Theatre

Revision ID: c6d59fca1da8
Revises: 33a82e44aa64
Create Date: 2022-04-18 17:54:22.408354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d59fca1da8'
down_revision = '33a82e44aa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
