"""New video fields

Revision ID: d8d27570171a
Revises: 999adb8b9abe
Create Date: 2022-04-02 16:15:53.747810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d27570171a'
down_revision = '999adb8b9abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('width', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bit_rate', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frame_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('file_size')
        batch_op.drop_column('frame_rate')
        batch_op.drop_column('bit_rate')
        batch_op.drop_column('height')
        batch_op.drop_column('width')

    # ### end Alembic commands ###
