"""Content tag relationship

Revision ID: dbc8234e83d4
Revises: 62c72beebf73
Create Date: 2022-03-22 22:06:12.396009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc8234e83d4'
down_revision = '62c72beebf73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
