"""New Theatre relationship

Revision ID: de533c35c545
Revises: c6d59fca1da8
Create Date: 2022-04-18 18:22:11.533977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de533c35c545'
down_revision = 'c6d59fca1da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
