"""Hybrid methods

Revision ID: e4fb334d0a61
Revises: 634c07b6db66
Create Date: 2022-04-16 02:05:17.279912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4fb334d0a61'
down_revision = '634c07b6db66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
