"""Duplicate field on deleted video

Revision ID: ebfe7ffd7fba
Revises: a5bd960ed142
Create Date: 2022-04-19 22:28:33.324118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfe7ffd7fba'
down_revision = 'a5bd960ed142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
