"""Theatre logo

Revision ID: ec2b4a3d8480
Revises: fcdee6c21b54
Create Date: 2022-04-18 03:59:33.605969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2b4a3d8480'
down_revision = 'fcdee6c21b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theatres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theatres', schema=None) as batch_op:
        batch_op.drop_column('logo_name')

    # ### end Alembic commands ###
