"""Create initial

Revision ID: ef5be7a7c9e3
Revises: 7f6200b1fdae
Create Date: 2022-03-19 18:12:23.971019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef5be7a7c9e3'
down_revision = '7f6200b1fdae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('migrate_version')
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('migrate_version',
    # sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    # sa.Column('repository_path', sa.TEXT(), nullable=True),
    # sa.Column('version', sa.INTEGER(), nullable=True),
    # sa.PrimaryKeyConstraint('repository_id')
    # )
    # ### end Alembic commands ###
    pass
