"""Theatres

Revision ID: fcdee6c21b54
Revises: 38cda3a81b3e
Create Date: 2022-04-18 02:15:35.569672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdee6c21b54'
down_revision = '38cda3a81b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('theatres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('from_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('to_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ongoing', sa.Boolean(), nullable=True))

    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theatre_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'theatres', ['theatre_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('theatre_id')

    with op.batch_alter_table('theatres', schema=None) as batch_op:
        batch_op.drop_column('ongoing')
        batch_op.drop_column('to_time')
        batch_op.drop_column('from_time')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
